### ISSUE TITLE
pcsx2 crashes when opening plugin settings for GSdx

### ISSUE THREAD

**Issue by haarp** [nE0sIghT/vortex-overlay#5]
The last log I get is "Trace/breakpoint trap", and an exit code of 133. There isn't much more unfortunately :(

This affects both 1.2.2 and 1.3.1-r1

**Comment by nE0sIghT** [comment]
Please post output of "emerge --info games-emulation/pcsx2"

**Comment by haarp** [comment]
http://pastebin.com/RfbgqS8A

**Comment by nE0sIghT** [comment]
Which version of wxGTK do you use? Also gdb backtrace will be useful

**Comment by haarp** [comment]
-9999 from today is also affected.

I'm using wxGTK-2.8.12.1-r3 from your overlay. I was also going to try 3.0 from your overlay, but that one fails to compile

I'll try to get a bt tomorrow.

**Comment by haarp** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0xf782fc65 in gtk_widget_style_get () from /usr/lib32/libgtk-x11-2.0.so.0
(gdb) bt
#0  0xf782fc65 in gtk_widget_style_get () from /usr/lib32/libgtk-x11-2.0.so.0
#1  0xf719638f in pthread_getspecific () from /lib32/libpthread.so.0
#2  0xf676660e in g_private_get () from /usr/lib32/libglib-2.0.so.0
#3  0xf7370364 in __bss_start () from /usr/lib32/libgobject-2.0.so.0
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

That's all I could get so far. I'm not very well versed in gdb tho. Does this seem like a pcsxs2 bug or is that related to running on Gentoo? If it's the former, I might go ahead and report the issue upstream instead.

**Comment by nE0sIghT** [comment]
Please run in gdb "thread apply all bt full" when sigsegv received and post
output
13 апр. 2015 г. 16:53 пользователь "haarp" notifications@github.com
написал:

**Comment by haarp** [comment]
(gdb) thread apply all bt full

```
Thread 3 (Thread 0xf2feeb40 (LWP 26735)):
#0  0xf7fd9ce0 in ?? ()
No symbol table info available.
#1  0x0809edba in VU_Thread::ExecuteRingBuffer (this=0x8db9070 <vu1Thread>)
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/pcsx2/MTVU.cpp:92
        lock = {_vptr.ScopedLockBool = 0xffffffff, m_lock = {_vptr.ScopedLock = 0xffffffff, m_lock = 0xffffffff, 
            m_IsLocked = false}, m_bool = @0xffffffff}
#2  0x0809ed91 in VU_Thread::ExecuteTaskInThread (this=0x8db9070 <vu1Thread>)
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/pcsx2/MTVU.cpp:85
No locals.
#3  0x08379848 in Threading::pxThread::_try_virtual_invoke (this=0x8db9070 <vu1Thread>, 
    method=&virtual Threading::pxThread::ExecuteTaskInThread())
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/common/src/Utilities/ThreadTools.cpp:545
No locals.
#4  0x08379d2b in Threading::pxThread::_internal_execute (this=0x8db9070 <vu1Thread>)
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/common/src/Utilities/ThreadTools.cpp:644
No locals.
#5  0x08379e67 in Threading::pxThread::_internal_callback (itsme=0x8db9070 <vu1Thread>)
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/common/src/Utilities/ThreadTools.cpp:684
        __clframe = {__cancel_routine = 0x8378220 <Threading::pxThread::_pt_callback_cleanup(void*)>, 
          __cancel_arg = 0x8db9070 <vu1Thread>, __do_it = 1, __cancel_type = 0}
        owner = @0x8db9070: {_vptr.pxThread = 0x83c2c08 <vtable for VU_Thread+8>, m_name = {<wxStringBase> = {
              static npos = 4294967295, m_pchData = 0xa06a9f4 L"MTVU"}, <No data fields>}, m_thread = 4076792640, 
          m_native_id = 4076792640, m_native_handle = 0, m_sem_event = {
            _vptr.Semaphore = 0x8486460 <vtable for Threading::Semaphore+8>, m_sema = {
              __size = "\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000", __align = 0}}, 
          m_sem_startup = {_vptr.Semaphore = 0x8486460 <vtable for Threading::Semaphore+8>, m_sema = {
              __size = "\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000", __align = 0}}, 
          m_mtx_InThread = {_vptr.Mutex = 0x84851c0 <vtable for Threading::Mutex+8>, m_mutex = {__data = {__lock = 1, 
                __count = 0, __owner = 26735, __kind = 0, __nusers = 1, {__elision_data = {__espins = 0, 
                    __elision = 0}, __list = {__next = 0x0}}}, 
              __size = "\001\000\000\000\000\000\000\000oh\000\000\000\000\000\000\001\000\000\000\000\000\000", 
              __align = 1}}, m_mtx_start = {<Threading::Mutex> = {
---Type <return> to continue, or q <return> to quit---
              _vptr.Mutex = 0x84851a8 <vtable for Threading::MutexRecursive+8>, m_mutex = {__data = {__lock = 0, 
                  __count = 0, __owner = 0, __kind = 1, __nusers = 0, {__elision_data = {__espins = 0, 
                      __elision = 0}, __list = {__next = 0x0}}}, 
                __size = '\000' <repeats 12 times>, "\001\000\000\000\000\000\000\000\000\000\000", 
                __align = 0}}, <No data fields>}, m_mtx_ThreadName = {
            _vptr.Mutex = 0x84851c0 <vtable for Threading::Mutex+8>, m_mutex = {__data = {__lock = 0, __count = 0, 
                __owner = 0, __kind = 0, __nusers = 0, {__elision_data = {__espins = 0, __elision = 0}, __list = {
                    __next = 0x0}}}, __size = '\000' <repeats 23 times>, __align = 0}}, m_detached = 0, 
          m_running = 1, m_except = {m_ptr = 0x0, m_mtx = {_vptr.Mutex = 0x84851c0 <vtable for Threading::Mutex+8>, 
              m_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __kind = 0, __nusers = 0, {__elision_data = {
                      __espins = 0, __elision = 0}, __list = {__next = 0x0}}}, __size = '\000' <repeats 23 times>, 
                __align = 0}}}, m_evtsrc_OnDelete = {
            _vptr.EventSource = 0x8487c08 <vtable for EventSource<Threading::EventListener_Thread>+8>, 
            m_listeners = empty std::list, m_cache_copy = empty std::list, m_cache_valid = false, m_listeners_lock = {
              _vptr.Mutex = 0x84851c0 <vtable for Threading::Mutex+8>, m_mutex = {__data = {__lock = 0, __count = 0, 
                  __owner = 0, __kind = 0, __nusers = 0, {__elision_data = {__espins = 0, __elision = 0}, __list = {
                      __next = 0x0}}}, __size = '\000' <repeats 23 times>, __align = 0}}}}
#6  0xf71910db in start_thread () from /lib32/libpthread.so.0
No symbol table info available.
#7  0xf70dc31e in clone () from /lib32/libc.so.6
No symbol table info available.

Thread 2 (Thread 0xf3a06b40 (LWP 26733)):
#0  0xf7fd9ce0 in ?? ()
No symbol table info available.
#1  0x083767c4 in Threading::Semaphore::WaitNoCancel (this=0xffffb79c)
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/common/src/Utilities/Semaphore.cpp:157
        oldstate = 0
#2  0x08380e14 in SynchronousActionState::WaitForResult (this=0xffffb794)
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/common/src/Utilities/wxAppWithHelpers.cpp:87
No locals.
#3  0x081e8384 in BaseSysExecEvent_ScopedCore::_post_and_wait (this=0xa3b18a8, core=...)
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/pcsx2/gui/AppCoreThread.cpp:567
        lock = {_vptr.ScopedLock = 0x8485198 <vtable for Threading::ScopedLock+8>, m_lock = 0xffffb7b8, 
---Type <return> to continue, or q <return> to quit---
          m_IsLocked = true}
#4  0x081e51c0 in SysExecEvent_SaveSinglePlugin::InvokeEvent (this=0xa3b18a8)
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/pcsx2/gui/AppCorePlugins.cpp:571
        plugstore = {m_ptr = 0x0}
        paused_core = {<BaseScopedCoreThread> = {<IScopedCoreThread> = {
              _vptr.IScopedCoreThread = 0x83f68a0 <vtable for ScopedCoreThreadPause+8>}, m_allowResume = false, 
            m_alreadyStopped = true, m_alreadyScoped = false, m_sync = {
              _vptr.SynchronousActionState = 0x83f6a80 <vtable for SynchronousActionState+8>, m_posted = false, 
              m_sema = {_vptr.Semaphore = 0x8486460 <vtable for Threading::Semaphore+8>, m_sema = {
                  __size = "\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000", __align = 0}}, 
              m_exception = {m_ptr = 0x0}, return_value = 0}, m_sync_resume = {
              _vptr.SynchronousActionState = 0x83f6a80 <vtable for SynchronousActionState+8>, m_posted = false, 
              m_sema = {_vptr.Semaphore = 0x8486460 <vtable for Threading::Semaphore+8>, m_sema = {
                  __size = "\000\000\000\000\200\000\000\000\000\000\000\000\326\356", <incomplete sequence \367>, 
                  __align = 0}}, m_exception = {m_ptr = 0x0}, return_value = 0}, m_mtx_resume = {
              _vptr.Mutex = 0x84851c0 <vtable for Threading::Mutex+8>, m_mutex = {__data = {__lock = 0, __count = 0, 
                  __owner = 0, __kind = 0, __nusers = 0, {__elision_data = {__espins = 0, __elision = 0}, __list = {
                      __next = 0x0}}}, __size = '\000' <repeats 23 times>, __align = 0}}}, <No data fields>}
#5  0x0823b9ab in SysExecEvent::_DoInvokeEvent (this=0xa3b18a8)
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/pcsx2/gui/ExecutorThread.cpp:122
No locals.
#6  0x0823be62 in pxEvtQueue::ProcessEvents (this=0xa097fd8, list=empty std::list, isIdle=false)
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/pcsx2/gui/ExecutorThread.cpp:218
        qpc_end = 592052827912667185
        deleteMe = {m_ptr = 0xa3b18a8}
        synclock = {_vptr.ScopedLock = 0x8485198 <vtable for Threading::ScopedLock+8>, m_lock = 0xa097fec, 
          m_IsLocked = false}
        node = 
#7  0x0823c113 in pxEvtQueue::ProcessPendingEvents (this=0xa097fd8)
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/pcsx2/gui/ExecutorThread.cpp:248
No locals.
#8  0x0823d079 in ExecutorThread::ExecuteTaskInThread (this=0xa097e64)
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/pcsx2/gui/ExecutorThread.cpp:543
No locals.
---Type <return> to continue, or q <return> to quit---
#9  0x08379848 in Threading::pxThread::_try_virtual_invoke (this=0xa097e64, 
    method=&virtual Threading::pxThread::ExecuteTaskInThread())
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/common/src/Utilities/ThreadTools.cpp:545
No locals.
#10 0x08379d2b in Threading::pxThread::_internal_execute (this=0xa097e64)
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/common/src/Utilities/ThreadTools.cpp:644
No locals.
#11 0x08379e67 in Threading::pxThread::_internal_callback (itsme=0xa097e64)
    at /var/tmp/portage/games-emulation/pcsx2-1.3.1/work/pcsx2-1.3.1/common/src/Utilities/ThreadTools.cpp:684
        __clframe = {__cancel_routine = 0x8378220 <Threading::pxThread::_pt_callback_cleanup(void*)>, 
          __cancel_arg = 0xa097e64, __do_it = 1, __cancel_type = 0}
        owner = @0xa097e64: {_vptr.pxThread = 0x844e2e8 <vtable for ExecutorThread+8>, m_name = {<wxStringBase> = {
              static npos = 4294967295, m_pchData = 0xa09803c L"SysExecutor"}, <No data fields>}, 
          m_thread = 4087376704, m_native_id = 4087376704, m_native_handle = 0, m_sem_event = {
            _vptr.Semaphore = 0x8486460 <vtable for Threading::Semaphore+8>, m_sema = {
              __size = "\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000", __align = 0}}, 
          m_sem_startup = {_vptr.Semaphore = 0x8486460 <vtable for Threading::Semaphore+8>, m_sema = {
              __size = "\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000", __align = 0}}, 
          m_mtx_InThread = {_vptr.Mutex = 0x84851c0 <vtable for Threading::Mutex+8>, m_mutex = {__data = {__lock = 1, 
                __count = 0, __owner = 26733, __kind = 0, __nusers = 1, {__elision_data = {__espins = 0, 
                    __elision = 0}, __list = {__next = 0x0}}}, 
              __size = "\001\000\000\000\000\000\000\000mh\000\000\000\000\000\000\001\000\000\000\000\000\000", 
              __align = 1}}, m_mtx_start = {<Threading::Mutex> = {
              _vptr.Mutex = 0x84851a8 <vtable for Threading::MutexRecursive+8>, m_mutex = {__data = {__lock = 0, 
                  __count = 0, __owner = 0, __kind = 1, __nusers = 0, {__elision_data = {__espins = 0, 
                      __elision = 0}, __list = {__next = 0x0}}}, 
                __size = '\000' <repeats 12 times>, "\001\000\000\000\000\000\000\000\000\000\000", 
                __align = 0}}, <No data fields>}, m_mtx_ThreadName = {
            _vptr.Mutex = 0x84851c0 <vtable for Threading::Mutex+8>, m_mutex = {__data = {__lock = 0, __count = 0, 
                __owner = 0, __kind = 0, __nusers = 0, {__elision_data = {__espins = 0, __elision = 0}, __list = {
                    __next = 0x0}}}, __size = '\000' <repeats 23 times>, __align = 0}}, m_detached = 0, 
          m_running = 1, m_except = {m_ptr = 0x0, m_mtx = {_vptr.Mutex = 0x84851c0 <vtable for Threading::Mutex+8>, 
              m_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __kind = 0, __nusers = 0, {__elision_data = {
                      __espins = 0, __elision = 0}, __list = {__next = 0x0}}}, __size = '\000' <repeats 23 times>, 
---Type <return> to continue, or q <return> to quit---
                __align = 0}}}, m_evtsrc_OnDelete = {
            _vptr.EventSource = 0x8487c08 <vtable for EventSource<Threading::EventListener_Thread>+8>, 
            m_listeners = empty std::list, m_cache_copy = empty std::list, m_cache_valid = false, m_listeners_lock = {
              _vptr.Mutex = 0x84851c0 <vtable for Threading::Mutex+8>, m_mutex = {__data = {__lock = 0, __count = 0, 
                  __owner = 0, __kind = 0, __nusers = 0, {__elision_data = {__espins = 0, __elision = 0}, __list = {
                      __next = 0x0}}}, __size = '\000' <repeats 23 times>, __align = 0}}}}
#12 0xf71910db in start_thread () from /lib32/libpthread.so.0
No symbol table info available.
#13 0xf70dc31e in clone () from /lib32/libc.so.6
No symbol table info available.

Thread 1 (Thread 0xf58aca00 (LWP 26726)):
#0  0xf782fc65 in gtk_widget_style_get () from /usr/lib32/libgtk-x11-2.0.so.0
No symbol table info available.
#1  0xf719638f in pthread_getspecific () from /lib32/libpthread.so.0
No symbol table info available.
#2  0xf676660e in g_private_get () from /usr/lib32/libglib-2.0.so.0
No symbol table info available.
#3  0xf7370364 in __bss_start () from /usr/lib32/libgobject-2.0.so.0
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by nE0sIghT** [comment]
Please try to run pcsx2 in new clean profile and if crash repeats report upstream. I don't think it is Gentoo specific.
